version:  '3.1'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      -  Mongo_Host=mongodb
    depends_on:
      - mongodb  

  mongodb:
    image: mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME: root
      - MONGO_INITDB_ROOT_PASSWORD: pass
      Volumes: 
        - mongo-data:/data/db

volumes:
    mongo-data: